"""Image generation backends. All three implement the same `generate(...)` signature.

- `PillowPlaceholderGenerator` — offline default. Renders a branded placeholder
  using Pillow + bundled font. No network, no API key.
- `PollinationsGenerator` — free Flux image gen via Pollinations.ai. No API key.
- `GeminiGenerator` — Google Gemini image model. Requires GEMINI_API_KEY.
"""

from __future__ import annotations

import logging
import os
import time
import urllib.parse
from pathlib import Path
from typing import Protocol

import requests
from PIL import Image, ImageDraw, ImageFont

from .brand import Brand

log = logging.getLogger(__name__)


class Generator(Protocol):
    def generate(self, prompt: str, output_path: str | Path, *, width: int, height: int) -> Path: ...


# ── 1. Offline placeholder ────────────────────────────────────────────────────

class PillowPlaceholderGenerator:
    """Renders a clean placeholder image using brand colors and the prompt text.

    Result is a real image file, recognisable as 'not the real one', so demo
    runs produce inspectable output without burning any image-gen quota.
    """

    def __init__(self, brand: Brand | None = None):
        self.brand = brand

    def _font(self, size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
        candidates = [
            "/System/Library/Fonts/Supplemental/Arial.ttf",
            "/Library/Fonts/Arial.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        ]
        for c in candidates:
            if Path(c).exists():
                try:
                    return ImageFont.truetype(c, size)
                except OSError:
                    continue
        return ImageFont.load_default()

    def generate(self, prompt: str, output_path: str | Path, *, width: int = 1920, height: int = 1080) -> Path:
        if self.brand:
            bg = self.brand.colors.get("background_grey", (246, 246, 246))
            ink = self.brand.colors.get("primary_blue", (0, 96, 217))
            accent = self.brand.colors.get("highlight_orange", (255, 175, 0))
        else:
            bg, ink, accent = (246, 246, 246), (0, 96, 217), (255, 175, 0)

        img = Image.new("RGB", (width, height), bg)
        draw = ImageDraw.Draw(img)

        # accent bar at top
        draw.rectangle([0, 0, width, height // 32], fill=accent)

        # "PLACEHOLDER" label
        small_font = self._font(max(28, height // 36))
        draw.text((width // 18, height // 9), "PLACEHOLDER", fill=ink, font=small_font)

        # Prompt text, wrapped
        title_font = self._font(max(36, height // 18))
        words = prompt.split()
        lines: list[str] = []
        line = ""
        max_chars = max(28, width // 60)
        for w in words:
            if len(line) + len(w) + 1 > max_chars:
                lines.append(line.strip()); line = w
            else:
                line = (line + " " + w) if line else w
        if line:
            lines.append(line.strip())

        y = height // 4
        for ln in lines[:6]:
            draw.text((width // 18, y), ln, fill=ink, font=title_font)
            y += title_font.size + 12

        # footer line
        footer = f"Generated by {self.brand.name if self.brand else 'demo'} placeholder generator"
        foot_font = self._font(max(22, height // 50))
        draw.text((width // 18, height - height // 12), footer, fill=ink, font=foot_font)

        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        img.save(out, "PNG", optimize=True)
        return out


# ── 2. Pollinations.ai (free Flux) ────────────────────────────────────────────

class PollinationsGenerator:
    ENDPOINT = "https://image.pollinations.ai/prompt"
    RETRIES = (3, 8, 20)

    def __init__(self, model: str = "flux"):
        self.model = model

    def generate(self, prompt: str, output_path: str | Path, *, width: int = 1920, height: int = 1080) -> Path:
        encoded = urllib.parse.quote(prompt, safe="")
        url = f"{self.ENDPOINT}/{encoded}"
        params = {"width": width, "height": height, "model": self.model, "nologo": "true", "enhance": "true"}
        last_err: Exception | None = None
        for attempt, delay in enumerate((0, *self.RETRIES)):
            if delay:
                log.warning("retry in %ds (attempt %d)", delay, attempt + 1)
                time.sleep(delay)
            try:
                r = requests.get(url, params=params, timeout=90)
                r.raise_for_status()
                if len(r.content) < 1000:
                    raise RuntimeError(f"response too small ({len(r.content)} bytes)")
                out = Path(output_path)
                out.parent.mkdir(parents=True, exist_ok=True)
                out.write_bytes(r.content)
                return out
            except Exception as e:  # noqa: BLE001
                last_err = e
        raise RuntimeError(f"Pollinations failed after retries: {last_err}")


# ── 3. Gemini ─────────────────────────────────────────────────────────────────

class GeminiGenerator:
    DEFAULT_MODEL = "gemini-2.5-flash-image"

    def __init__(self, api_key: str | None = None, model: str | None = None):
        self.api_key = api_key or os.environ["GEMINI_API_KEY"]
        self.model = model or self.DEFAULT_MODEL

    def generate(self, prompt: str, output_path: str | Path, *, width: int = 1920, height: int = 1080) -> Path:
        from google import genai
        client = genai.Client(api_key=self.api_key)
        resp = client.models.generate_content(model=self.model, contents=[prompt])
        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        for part in resp.parts:
            if getattr(part, "inline_data", None) is not None:
                part.as_image().save(out)
                return out
        raise RuntimeError("Gemini returned no image part")


# ── factory ───────────────────────────────────────────────────────────────────

def get(name: str | None = None, brand: Brand | None = None) -> Generator:
    name = (name or os.environ.get("IMAGE_BACKEND") or "").lower()
    if not name or name in {"placeholder", "stub", "offline"}:
        return PillowPlaceholderGenerator(brand=brand)
    if name == "pollinations":
        return PollinationsGenerator()
    if name == "gemini":
        return GeminiGenerator()
    raise ValueError(f"Unknown backend: {name!r}. Use placeholder | pollinations | gemini.")
